name: MobHunting
main: one.lindegaard.MobHunting.MobHunting
version: ${version}
description: A Mobhunting plugin
dev-url: http://dev.bukkit.org/server-mods/mobhunting/
author: Rocologo
depend: [Vault]
softdepend: [Multiverse-Core, Essentials, WorldEdit, WorldGuard, PreciousStones, HolographicDisplays, Holograms, Factions, Towny, Rdesidence, ProtocolLib, mcMMO, BossShop, MythicMobs, TARDISWeepingAngels, Citizens, Sentry, Sentinel, Minigames, MinigamesLib, MyPet, MobArena, PVPArena, BattleArena, LibsDisguises, DisguiseCraft, iDisguise, VanishNoPacket, BossBarAPI, BarAPI, ActionBar, TitleAPI, TitleManager, PlaceholderAPI, MobStacker, Gringotts, ActionBarAPI, ActionAnnouncer, CustomMobs, ConquestiaMobs, StackMob, MysteriousHalloween, SmartGiants, ExtraHardMode, CrackShot]

commands:
  mobhunt:
    description: Allows you to configure mob hunt
    permission: mobhunting.cmd
    aliases: [mob,mh,mobhunt]
    usage: /<command> command

permissions:
  mobhunting.enable:
    description: Allows mobhunting to be enabled for a player
    default: true
  mobhunting.cmd:
    description: Allows a player to use the mobhunt command
    default: true
  mobhunting.reload:
    description: Allows a player to reload the config
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.update:
    description: Allows a player to update the plugin
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.region:
    description: Allows a player to set Worldguard custom flag MobHunting
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.achievements.disabled:
    description: Reject a player to get Achievements. 
    default: false
  mobhunting.listachievements:
    description: Allows a player to see all their achievements
    default: true
    children:
      mobhunting.cmd: true    
  mobhunting.listachievements.other:
    description: Allows a player to see another players achievements
    default: op
    children:
      mobhunting.listachievements: true
  mobhunting.checkgrinding:
    description: Allows a player to check whether the region they are in is a known grinding area 
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.cleargrinding:
    description: Allows a player to remove grinding areas 
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.whitelistarea:
    description: Allows a player to whitelist an grinding area.
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.blacklistlistarea:
    description: Allows a player to blacklist an grinding area.
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.top:
    description: Allows a player to check the top player stats
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.leaderboard:
    description: Allows a player to create, edit, and delete leaderboards
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.select:
    description: Allows you to select points for leaderboards if WorldEdit is not installed
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.learn:
    description: Allows you to toggle the learning mode on and off
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.mute:
    description: Allows you to toggle the muting mode on and off
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.npc:
    description: Allows you to create and delete Citizen2 NPCs
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.reload:
    description: Allows you to reload the configuration
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.database:
    description: Allows you to do database operations.
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.version:
    description: Allows you to get plugin version.
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.head:
    description: Allows the player to give heads to other players.
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.bounty:
    description: Allows you to put a bounty on other player.
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.debug:
    description: Allows you to enable/disable debugmode and see debug information in the server console.
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.learn:
    description: Allows you to enable/disable learningmode and see learning information when you kill a mob.
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.learn.other:
    description: Allows you to enable/disable learningmode for other players.
    default: op
    children:
      mobhunting.learn: true
  mobhunting.mute:
    description: Allows you to mute/unmute most messages in the chat.
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.mute.other:
    description: Allows you to mute/unmute most messages in the chat for other players.
    default: op
    children:
      mobhunting.mute: true
  mobhunting.money.give:
    description: Allows you to give a player bag of gold
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.money.take:
    description: Allows you to take bag of gold from a player
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.money.drop:
    description: Allows you to drop bag of gold on the ground
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.money.sell:
    description: Allows you to sell your bag of gold and get money
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.money.buy:
    description: Allows you to buy bag of gold.
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.money.shop:
    description: Allows you to open the MobHunting BossShop.
    default: true
    children:
      mobhunting.cmd: true
  mobhunting.happyhour:
    description: Allows you to start a happyhour for some time
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.bagofgoldsign.use:
    description: Allows you to use Bag of gold signs
    default: true
  mobhunting.bagofgoldsign.create:
    description: Allows you to create Bag of gold signs
    default: op
  mobhunting.bagofgoldsign.destroy:
    description: Allows you to destroy Bag of gold signs
    default: op



